const CONFIG = {
  START_DATE: new Date(2026, 8, 13),
  END_DATE: new Date(2026, 10, 21),
  siteName: "OZDLE",
};


const WORDLE_WORDS = [
  "ELPHABA",
  "GOOD",
  "NESSA",
  "GRANDE",
  "PINK",
  "DEAREST",
  "BROOM",
  "GLINDA",
  "YEOH",
  "WIZARD",
  "JOHNNY",
  "GELPHIE",
  "DEFY",
  "ARIANA",
  "GREEN",
  "CYNTHIA",
  "HUNG",
  "DOOR",
  "ELPHIE",
  "MARCH",
  "POPULAR",
  "BODE",
  "THROPP",
  "WITCH",
  "GALINDA",
  "SHIZ",
  "BAILEY",
  "MAGIC",
  "GRAVITY",
  "ERIVO",
  "UPLAND",
  "DEED",
  "FEELING",
  "SPACE",
  "BUBBLE",
  "WEST",
  "DANCING",
  "MOURN",
  "HUNTER",
  "HOLDING",
  "SWEET",
  "OZDUST",
  "WICKED",
].filter((word, i, arr) =>
  arr.findIndex(w => w.toUpperCase() === word.toUpperCase()) === i
); 

const SQUAREDLE_PUZZLES = [
  { theme: "Thank Goodness!", letters: "KNDYBPIAUBGLHNBE", words: ["PINK", "HUNG", "BUBBLE", "GAY", "GLINDA"] },
  { theme: "It's Me!", letters: "ZWHSGIEPCRLEKEDN", words: ["WICKED", "GREEN", "GIRL", "ELPHIE", "SHIZ"] },
  { theme: "Wicked Songs", letters: "IWLWAMTISONDBDTG", words: ["NOMTW", "DOS", "TWAI", "SB", "DTL", "INTG", "OSD", "ASM", "DG"] },
  { theme: "Wicked: For Good Songs", letters: "LPGDHTNIBWTBCIOM", words: ["TG", "ICBH", "NPLH", "NGD", "MOTWH", "TGITB"] },
  { theme: "Expressification", letters: "SSEDEUATOSLIZBHZ", words: ["OBSESSULATED", "OZ", "SHIZ"] },
  { theme: "Charmed", letters: "GUINBRETYEOOHAGD", words: ["TIN", "HAY", "RUBY", "GREEN", "GOOD"] },
  { theme: "Oh", letters: "RIMMLGXEEPRITAHE", words: ["GRIMMERIE", "HAT", "ELIXIR", "ELPHIE"] },
  { theme: "Cast", letters: "FFHBNNEOIYJDRACO", words: ["ARI", "CYN", "JOHNNY", "BODE", "YEOH", "JEFF"] },
  { theme: "When In Oz", letters: "RIMEAEKULHNIDCNW", words: ["EMERALD", "MUNCHKIN", "WINKIE"] },
  { theme: "Dearest, Darlingest, Momsie And Popsicle", letters: "IBDMCUEAOLANSCER", words: ["LARENA", "MELENA", "DULCIBEAR", "OSCAR"] },
  { theme: "Sobriquet", letters: "SORTGUPHDGPLINAE", words: ["UPLAND", "THROPP", "DIGGS", "GALE"] },
  { theme: "Everywhere", letters: "EENAMBRISWOAYKDL", words: ["RAINBOW", "ROAD", "EMERALD", "SKY"] },
  { theme: "Must be Seen, Not Heard", letters: "BEKLYENISAOHTRMG", words: ["MONKEY", "GOAT", "BEAR", "LION", "HORSE"] },
  { theme: "We Deserve Each Other", letters: "CORMSHECWUSFLIFW", words: ["SWIFFER", "CROCS", "REM", "LUSH"] },
  { theme: "Behind The Curtain", letters: "TNHNMYROANAJLUPD", words: ["JON", "DANA", "PAUL", "MYRON", "JOHN"] },
  { theme: "When in...", letters: "YOLENPRUDIAKSONG", words: ["PARIS", "LONDON", "SINGAPORE", "YORK", "PAULO"] },
  { theme: "Well, We Can't All Come And Go By...", letters: "TMSEORBLOUABBHNI", words: ["BUBBLE", "TRAIN", "BROOM", "HORSE"] },
  { theme: "Look to the Western...", letters: "RAZWNDIOEUELRRSR", words: ["SURRENDER", "WIZARD", "LIES", "DIES", "OZ"] },
  { theme: "I Didn't Know That Was Happening..", letters: "FLECDOIAEISPVTCH", words: ["ITCH", "SPACE", "FLIP", "CIEL", "VIDEOS"] },
  { theme: "So if You Care to Find Them!", letters: "DRRVYEOIGMSKZUAN", words: ["DEGUZMAN", "ERIVO", "MORRISEY", "VOSK"] },
  { theme: "It's Good to See Them, Isn't it?", letters: "YDNAETRGZMLIUAMH", words: ["GRANDE", "MAUZEY", "TRIMM", "HILTY"] },
  { theme: "It's About The Girls, Stupid!", letters: "TPHILEERBUWOQDOS", words: ["BLUE", "SWEET", "ELPHIE", "DOOR", "QUEER"] },
];
